# Generated by Django 5.0.1 on 2024-01-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aim_CheckboxOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('lga', models.CharField(blank=True, max_length=50, null=True)),
                ('locality', models.CharField(blank=True, max_length=50, null=True)),
                ('govtID', models.CharField(blank=True, max_length=50, null=True)),
                ('employment', models.BooleanField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=20, null=True)),
                ('bankAccount', models.BooleanField(blank=True, null=True)),
                ('noBankReason', models.CharField(blank=True, max_length=255, null=True)),
                ('disability', models.BooleanField(blank=True, null=True)),
                ('disabilityType', models.CharField(blank=True, max_length=255, null=True)),
                ('computerLiteracy', models.CharField(blank=True, max_length=50, null=True)),
                ('familiar', models.BooleanField(blank=True, null=True)),
                ('hasComputer', models.BooleanField(blank=True, null=True)),
                ('availability', models.BooleanField(blank=True, null=True)),
                ('majorProgram', models.CharField(blank=True, max_length=50, null=True)),
                ('majorProgramInterest', models.CharField(blank=True, max_length=50, null=True)),
                ('optionalProgram', models.CharField(blank=True, max_length=50, null=True)),
                ('optionalProgramInterest', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckboxOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='hearAbout_CheckboxOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='program_CheckboxOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
            ],
        ),
    ]
