# Generated by Django 5.0.1 on 2024-01-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('qualification', models.CharField(choices=[('Secondary School', 'Secondary School'), ('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], default=None, max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('lga', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('govtID', models.CharField(choices=[('None', 'None'), ("Driver's License", "Driver's License"), ('National ID Card', 'National ID Card'), ("Voter's Card", "Voter's Card")], max_length=50)),
                ('employment', models.BooleanField()),
                ('occupation', models.CharField(blank=True, max_length=20, null=True)),
                ('bankAccount', models.BooleanField()),
                ('noBankReason', models.CharField(blank=True, max_length=255, null=True)),
                ('disability', models.BooleanField()),
                ('disabilityType', models.CharField(blank=True, max_length=255, null=True)),
                ('computerLiteracy', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced User', 'Advanced User')], default=None, max_length=50)),
                ('packages', models.CharField(choices=[('MS-Word', 'MS-Word'), ('MS-Excel', 'MS-Excel'), ('MS-PowerPoint', 'MS-PowerPoint'), ('Graphics and Design e.g AutoCAD, Photoshop', 'Graphics and Design e.g AutoCAD, Photoshop'), ('Programming, Statistical and Data Analyses', 'Programming, Statistical and Data Analyses')], default=None, max_length=255)),
                ('familiar', models.BooleanField()),
                ('hasComputer', models.BooleanField()),
                ('availability', models.BooleanField()),
                ('interestLevel', models.CharField(choices=[('Not Interested', 'Not Interested'), ('Interested', 'Interested')], default=None, max_length=50)),
                ('program', models.CharField(choices=[('GIS Technology', 'GIS Technology (Virtual Learning) – 2 months'), ('Drone Technology', 'Drone Technology (Hybrid – partly virtual and partly physical) – 1 month'), ('3D Design/Printing', '3D Design/Printing (Hybrid – partly virtual and partly physical) – 1 month')], default=None, max_length=255)),
                ('social_media_handle_facebook', models.CharField(max_length=255)),
                ('social_media_handle_linkedIn', models.CharField(max_length=255)),
                ('social_media_handle_X', models.CharField(max_length=255)),
                ('hearAbout', models.CharField(max_length=50)),
                ('aim', models.CharField(choices=[('Skills acquisition', 'Skills acquisition'), ('Self-development', 'Self-development'), ('Employment', 'Employment')], default=None, max_length=50)),
            ],
        ),
    ]
