# Generated by Django 5.0.1 on 2024-01-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='social_media_handle_X',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='social_media_handle_facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='social_media_handle_linkedIn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
