# Generated by Django 5.0.1 on 2024-01-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_applicant_hearabout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='hasComputer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='lga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='locality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
