# Generated by Django 5.0.1 on 2024-01-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_alter_applicant_hascomputer_alter_applicant_lga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='govtID',
            field=models.CharField(choices=[('None', 'None'), ("Driver's License", "Driver's License"), ('National ID Card', 'National ID Card'), ("Voter's Card", "Voter's Card")], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='hearAbout',
            field=models.CharField(blank=True, choices=[('Twitter', 'Twitter'), ('Email Advert', 'Email Advert'), ('Facebook', 'Facebook'), ('Radio', 'Radio'), ('Newspaper', 'Newspaper'), ('Our Website', 'Our Website'), ('Google', 'Google'), ('LinkedIn', 'LinkedIn'), ('Instagram', 'Instagram'), ('TV', 'TV'), ('WhatsApp', 'WhatsApp'), ('Others', 'Others')], default=None, max_length=50, null=True),
        ),
    ]
