# Generated by Django 5.0.1 on 2024-01-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_applicant_form_opened_at_applicant_form_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='aim',
            field=models.ManyToManyField(to='enrollment.aim_checkboxoption'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='hearAbout',
            field=models.ManyToManyField(to='enrollment.hearabout_checkboxoption'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='hearAboutother',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
