# Generated by Django 5.0.1 on 2024-01-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_applicant_aim_applicant_hearabout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='packages',
            field=models.ManyToManyField(to='enrollment.checkboxoption'),
        ),
    ]
