# Generated by Django 5.0.1 on 2024-01-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_alter_applicant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='aim',
            field=models.CharField(blank=True, choices=[('Skills acquisition', 'Skills acquisition'), ('Self-development', 'Self-development'), ('Employment', 'Employment')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='availability',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='bankAccount',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='computerLiteracy',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced User', 'Advanced User')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='disability',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='dob',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='employment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='familiar',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='govtID',
            field=models.CharField(blank=True, choices=[('None', 'None'), ("Driver's License", "Driver's License"), ('National ID Card', 'National ID Card'), ("Voter's Card", "Voter's Card")], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='packages',
            field=models.CharField(blank=True, choices=[('MS-Word', 'MS-Word'), ('MS-Excel', 'MS-Excel'), ('MS-PowerPoint', 'MS-PowerPoint'), ('Graphics and Design e.g AutoCAD, Photoshop', 'Graphics and Design e.g AutoCAD, Photoshop'), ('Programming, Statistical and Data Analyses', 'Programming, Statistical and Data Analyses')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='program',
            field=models.CharField(blank=True, choices=[('GIS Technology', 'GIS Technology (Virtual Learning) – 2 months'), ('Drone Technology', 'Drone Technology (Hybrid – partly virtual and partly physical) – 1 month'), ('3D Design/Printing', '3D Design/Printing (Hybrid – partly virtual and partly physical) – 1 month')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='qualification',
            field=models.CharField(blank=True, choices=[('Secondary School', 'Secondary School'), ('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], default=None, max_length=50, null=True),
        ),
    ]
