# Generated by Django 5.0.1 on 2024-01-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_alter_applicant_aim_alter_applicant_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='interestLevel',
            field=models.CharField(blank=True, choices=[('Not Interested', 'Not Interested'), ('Interested', 'Interested')], default=None, max_length=50, null=True),
        ),
    ]
