# Generated by Django 5.0.1 on 2024-01-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0009_applicant_dob_applicant_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='qualification',
            field=models.CharField(blank=True, choices=[('Secondary School', 'Secondary School'), ('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], default=None, max_length=50, null=True),
        ),
    ]
