# Generated by Django 5.0.1 on 2024-01-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0010_applicant_email_applicant_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='lga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='locality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
