# Generated by Django 5.0.1 on 2024-01-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0011_applicant_lga_applicant_locality_applicant_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='bankAccount',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='employment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='govtID',
            field=models.CharField(blank=True, choices=[('None', 'None'), ("Driver's License", "Driver's License"), ('National ID Card', 'National ID Card'), ("Voter's Card", "Voter's Card")], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='noBankReason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='occupation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
