# Generated by Django 5.0.1 on 2024-01-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0012_applicant_bankaccount_applicant_employment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='computerLiteracy',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced User', 'Advanced User')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='disability',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='disabilityType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='packages',
            field=models.CharField(blank=True, choices=[('MS-Word', 'MS-Word'), ('MS-Excel', 'MS-Excel'), ('MS-PowerPoint', 'MS-PowerPoint'), ('Graphics and Design e.g AutoCAD, Photoshop', 'Graphics and Design e.g AutoCAD, Photoshop'), ('Programming, Statistical and Data Analyses', 'Programming, Statistical and Data Analyses')], default=None, max_length=255, null=True),
        ),
    ]
