# Generated by Django 5.0.1 on 2024-01-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0013_applicant_computerliteracy_applicant_disability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='computerLiteracy',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='packages',
        ),
    ]
