# Generated by Django 5.0.1 on 2024-01-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0014_remove_applicant_computerliteracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='computerLiteracy',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced User', 'Advanced User')], default=None, max_length=50, null=True),
        ),
    ]
