# Generated by Django 5.0.1 on 2024-01-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0016_applicant_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='packages',
        ),
    ]
