# Generated by Django 5.0.1 on 2024-01-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0017_remove_applicant_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='familiar',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
