# Generated by Django 5.0.1 on 2024-01-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0018_applicant_familiar'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='packages',
            field=models.CharField(blank=True, choices=[('MS-Word', 'MS-Word'), ('MS-Excel', 'MS-Excel'), ('MS-PowerPoint', 'MS-PowerPoint'), ('Graphics and Design e.g AutoCAD, Photoshop', 'Graphics and Design e.g AutoCAD, Photoshop'), ('Programming, Statistical and Data Analyses', 'Programming, Statistical and Data Analyses')], default=None, max_length=255, null=True),
        ),
    ]
