# Generated by Django 5.0.1 on 2024-01-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0019_applicant_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='packages',
        ),
        migrations.AddField(
            model_name='applicant',
            name='packages',
            field=models.ManyToManyField(to='enrollment.checkboxoption'),
        ),
    ]
