# Generated by Django 5.0.1 on 2024-01-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0020_checkboxoption_remove_applicant_packages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='packages',
            field=models.ManyToManyField(choices=[('MS-Word', 'MS-Word'), ('MS-Excel', 'MS-Excel'), ('MS-PowerPoint', 'MS-PowerPoint'), ('Graphics and Design e.g AutoCAD, Photoshop', 'Graphics and Design e.g AutoCAD, Photoshop'), ('Programming, Statistical and Data Analyses', 'Programming, Statistical and Data Analyses')], to='enrollment.checkboxoption'),
        ),
    ]
