# Generated by Django 5.0.1 on 2024-01-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0021_alter_applicant_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='packages',
        ),
        migrations.AddField(
            model_name='applicant',
            name='availability',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='hasComputer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='interestLevel',
            field=models.CharField(blank=True, choices=[('Not Interested', 'Not Interested'), ('Interested', 'Interested')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='social_media_handle_X',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='social_media_handle_facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='social_media_handle_linkedIn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
