# Generated by Django 5.0.1 on 2024-01-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0022_remove_applicant_packages_applicant_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='packages',
            field=models.ManyToManyField(to='enrollment.checkboxoption'),
        ),
    ]
