# Generated by Django 5.0.1 on 2024-01-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0024_program_checkboxoption_applicant_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='aim_CheckboxOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='hearAbout_CheckboxOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='aim',
            field=models.ManyToManyField(to='enrollment.aim_checkboxoption'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='hearAbout',
            field=models.ManyToManyField(to='enrollment.hearabout_checkboxoption'),
        ),
    ]
