# Generated by Django 5.0.1 on 2024-01-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0027_alter_applicant_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='program',
        ),
        migrations.AddField(
            model_name='applicant',
            name='majorProgram',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='majorProgramInterest',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='optionalProgram',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='optionalProgramInterest',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='computerLiteracy',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='govtID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='interestLevel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='qualification',
            field=models.CharField(max_length=50),
        ),
    ]
